#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Exchange Manager — Single-command installer
#
# Usage (run on the target machine):
#
#   curl -fsSL https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/YOUR_REPO/main/deploy/install.sh | bash
#
# Requirements: Docker 24+ with the Compose plugin (docker compose v2).
# Tested on: Ubuntu 22.04 / 24.04, Debian 12, RHEL 9, macOS 14.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Configuration — edit these two lines before sharing with customers ────────
GITHUB_OWNER="Ali-Younis"   # your GitHub username
GITHUB_REPO="Currency_Exchange"          # your GitHub repo name
BRANCH="main"
# ─────────────────────────────────────────────────────────────────────────────

RAW_BASE="https://raw.githubusercontent.com/${GITHUB_OWNER}/${GITHUB_REPO}/${BRANCH}/exchange-system/deploy"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/exchange-manager}"

# Accept GitHub PAT as first argument (required for private repos).
# Usage:  curl ... | bash -s -- ghp_YOUR_TOKEN
GH_TOKEN="${1:-${GH_TOKEN:-}}"

# Build curl auth options
if [[ -n "${GH_TOKEN}" ]]; then
  gh_curl() { curl -H "Authorization: token ${GH_TOKEN}" "$@"; }
else
  gh_curl() { curl "$@"; }
fi

# ── Terminal colours ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERR ]${NC}  $*"; exit 1; }
step()    { echo -e "\n${BOLD}── $* ──────────────────────────────────────${NC}"; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}${BOLD}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║       Exchange Manager  Installer        ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
step "Checking prerequisites"

command -v docker &>/dev/null \
  || error "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run."

docker compose version &>/dev/null \
  || error "Docker Compose plugin is not installed. See https://docs.docker.com/compose/install/"

info "Docker          $(docker --version | cut -d' ' -f3 | tr -d ',')"
info "Docker Compose  $(docker compose version --short)"

# ── 2. Create install directory ───────────────────────────────────────────────
step "Preparing install directory"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
info "Install path: ${BOLD}${INSTALL_DIR}${NC}"

# ── 3. Download configuration files ──────────────────────────────────────────
step "Downloading configuration files"

gh_curl -fsSL "${RAW_BASE}/docker-compose.yml" -o docker-compose.yml \
  || error "Failed to download docker-compose.yml — check your internet connection."
gh_curl -fsSL "${RAW_BASE}/nginx.conf"         -o nginx.conf \
  || error "Failed to download nginx.conf."

success "docker-compose.yml and nginx.conf downloaded."

# ── 4. Configure .env ─────────────────────────────────────────────────────────
step "Configuring environment"

if [[ -f .env ]]; then
  warn ".env already exists — skipping. Delete it and re-run to reconfigure."
else
  # Generate cryptographically random secrets
  if command -v openssl &>/dev/null; then
    JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
    DB_PASS=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 28)
  else
    JWT_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#%^&*' </dev/urandom 2>/dev/null | head -c 64)
    DB_PASS=$(LC_ALL=C tr -dc 'A-Za-z0-9'           </dev/urandom 2>/dev/null | head -c 28)
  fi

  # Prompt for public URL (used for CORS)
  echo ""
  echo -e "  Enter the public URL of this machine (e.g. ${BOLD}http://192.168.1.50${NC}"
  echo -e "  or ${BOLD}https://exchange.yourcompany.com${NC})."
  echo -e "  Press Enter to use ${BOLD}http://localhost${NC}:"
  read -r PUBLIC_URL
  PUBLIC_URL="${PUBLIC_URL:-http://localhost}"

  cat > .env <<EOF
# Exchange Manager — generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Keep this file private — it contains secrets.

GITHUB_OWNER=${GITHUB_OWNER}
IMAGE_TAG=latest

POSTGRES_USER=exchange_user
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=exchange_db

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=8h

HTTP_PORT=80
CORS_ORIGIN=${PUBLIC_URL}
EOF

  success ".env created with auto-generated secrets."
fi

# ── 5. Authenticate to GHCR (if images are private) ──────────────────────────
step "Container registry authentication"

# Try a dry-run pull to check if auth is needed
if docker manifest inspect "ghcr.io/${GITHUB_OWNER}/exchange-api:latest" &>/dev/null 2>&1; then
  success "Images are publicly accessible — no login required."
else
  echo ""
  warn "Images are private. You need a GitHub Personal Access Token (PAT)"
  warn "with the  read:packages  scope to pull them."
  echo ""
  echo -e "  Create a PAT at: ${BOLD}https://github.com/settings/tokens${NC}"
  echo -e "  Then enter it below (input is hidden):"
  echo ""
  read -r -s -p "  GitHub PAT: " GH_PAT
  echo ""
  echo "${GH_PAT}" | docker login ghcr.io -u "${GITHUB_OWNER}" --password-stdin \
    || error "GHCR login failed. Check your PAT and that it has 'read:packages' scope."
  success "Logged in to ghcr.io."
fi

# ── 6. Pull images ────────────────────────────────────────────────────────────
step "Pulling Docker images (this may take a few minutes on first install)"

docker compose pull

# ── 7. Start services ─────────────────────────────────────────────────────────
step "Starting Exchange Manager"

docker compose up -d

# ── 8. Wait for API health ────────────────────────────────────────────────────
step "Waiting for services to become healthy"

ATTEMPTS=0; MAX=36   # up to 3 minutes
echo -n "  "
until docker compose ps --format '{{.Service}} {{.Health}}' 2>/dev/null \
      | grep -q "^api healthy" || [[ $ATTEMPTS -ge $MAX ]]; do
  sleep 5
  ATTEMPTS=$((ATTEMPTS + 1))
  echo -n "."
done
echo ""

if [[ $ATTEMPTS -ge $MAX ]]; then
  warn "API is still starting up. Check logs with:"
  warn "  docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f api"
else
  success "All services are up and healthy!"
fi

# ── 9. Done ───────────────────────────────────────────────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")
HTTP_PORT_VAL=$(grep -E '^HTTP_PORT=' .env 2>/dev/null | cut -d= -f2 || echo "80")
PUBLIC_URL_VAL=$(grep -E '^CORS_ORIGIN=' .env 2>/dev/null | cut -d= -f2 || echo "http://${SERVER_IP}")

echo ""
echo -e "${GREEN}${BOLD}"
echo "  ╔════════════════════════════════════════════════════╗"
echo "  ║   Exchange Manager is running!                     ║"
echo "  ╠════════════════════════════════════════════════════╣"
printf  "  ║   Web UI:  %-40s║\n" "${PUBLIC_URL_VAL}  "
echo "  ║                                                    ║"
echo "  ║   Default login:  admin  /  admin1234              ║"
echo "  ║   ⚠  You will be forced to change the password     ║"
echo "  ║      on first login.                               ║"
echo "  ╚════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo "  Useful commands (run from ${BOLD}${INSTALL_DIR}${NC}):"
echo ""
echo "    View live logs:    docker compose logs -f"
echo "    Stop:              docker compose down"
echo "    Update to latest:  docker compose pull && docker compose up -d"
echo ""
