#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Exchange Manager — Single-command installer / updater
#
# Fresh install:
#   curl -fsSL https://raw.githubusercontent.com/Ali-Younis/Currency_Exchange/main/exchange-system/deploy/install.sh \
#     | bash -s -- "<YOUR_GITHUB_PAT>"
#
# Update an existing installation (run from the install directory):
#   bash install.sh "<YOUR_GITHUB_PAT>"
#
# Requirements: Docker 24+ with the Compose plugin (docker compose v2).
# Tested on: Ubuntu 22.04 / 24.04, Debian 12, RHEL 9, macOS 14.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
GITHUB_OWNER="ali-younis"          # must be lowercase — GHCR names are case-sensitive
GITHUB_REPO="Ali-Younis/Currency_Exchange"
REPO_BRANCH="main"
REPO_RAW="https://raw.githubusercontent.com/${GITHUB_REPO}/${REPO_BRANCH}"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/exchange-manager}"

# PAT passed as first argument (required for private GHCR images)
GH_PAT="${1:-}"
# ─────────────────────────────────────────────────────────────────────────────

# ── Terminal colours ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERR ]${NC}  $*"; exit 1; }
step()    { echo -e "\n${BOLD}── $* ──────────────────────────────────────${NC}"; }

# ── Detect update vs fresh install ───────────────────────────────────────────
IS_UPDATE=false
if [[ -f "${INSTALL_DIR}/.env" && -f "${INSTALL_DIR}/docker-compose.yml" ]]; then
  IS_UPDATE=true
fi

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}${BOLD}"
echo "  ╔══════════════════════════════════════════╗"
if $IS_UPDATE; then
echo "  ║     Exchange Manager  — Updater          ║"
else
echo "  ║     Exchange Manager  — Installer        ║"
fi
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
step "Checking prerequisites"

command -v docker &>/dev/null \
  || error "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run."

docker compose version &>/dev/null \
  || error "Docker Compose plugin is not installed. See https://docs.docker.com/compose/install/"

info "Docker          $(docker --version | cut -d' ' -f3 | tr -d ',')"
info "Docker Compose  $(docker compose version --short)"

# ── 2. Create / enter install directory ───────────────────────────────────────
step "Preparing install directory"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
info "Install path: ${BOLD}${INSTALL_DIR}${NC}"

# ── 3. Download latest configuration files from GitHub ───────────────────────
step "Downloading latest configuration from GitHub"

# Helper: download with optional PAT (for private repos)
gh_curl() {
  local url="$1" dest="$2"
  if [[ -n "${GH_PAT}" ]]; then
    curl -fsSL -H "Authorization: token ${GH_PAT}" "$url" -o "$dest"
  else
    curl -fsSL "$url" -o "$dest"
  fi
}

gh_curl "${REPO_RAW}/exchange-system/deploy/docker-compose.yml" docker-compose.yml
success "docker-compose.yml downloaded."

gh_curl "${REPO_RAW}/exchange-system/deploy/nginx.conf" nginx.conf
success "nginx.conf downloaded."

# ── 4. Configure .env ─────────────────────────────────────────────────────────
step "Configuring environment"

if $IS_UPDATE; then
  info ".env already exists — preserving existing secrets and settings."
  # Ensure GITHUB_OWNER is present (may be missing in very old installs)
  if ! grep -q "^GITHUB_OWNER=" .env; then
    echo "GITHUB_OWNER=${GITHUB_OWNER}" >> .env
    info "Added GITHUB_OWNER to existing .env."
  fi
else
  # Generate cryptographically random secrets
  if command -v openssl &>/dev/null; then
    JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
    DB_PASS=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 28)
  else
    JWT_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#%^&*' </dev/urandom 2>/dev/null | head -c 64)
    DB_PASS=$(LC_ALL=C tr -dc 'A-Za-z0-9'           </dev/urandom 2>/dev/null | head -c 28)
  fi

  # Prompt for public URL (used for CORS)
  echo ""
  echo -e "  Enter the public URL of this machine (e.g. ${BOLD}http://192.168.1.50${NC}"
  echo -e "  or ${BOLD}https://exchange.yourcompany.com${NC})."
  echo -e "  Press Enter to use ${BOLD}http://localhost${NC}:"
  read -r PUBLIC_URL
  PUBLIC_URL="${PUBLIC_URL:-http://localhost}"

  cat > .env <<EOF
# Exchange Manager — generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Keep this file private — it contains secrets.

GITHUB_OWNER=${GITHUB_OWNER}
IMAGE_TAG=latest

POSTGRES_USER=exchange_user
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=exchange_db

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=8h

HTTP_PORT=80
CORS_ORIGIN=${PUBLIC_URL}
EOF

  success ".env created with auto-generated secrets."
fi

# ── 5. Authenticate to GHCR ──────────────────────────────────────────────────
step "Container registry authentication"

# Try a dry-run manifest check to see if images are publicly accessible
if docker manifest inspect "ghcr.io/${GITHUB_OWNER}/exchange-api:latest" &>/dev/null 2>&1; then
  success "Images are publicly accessible — no login required."
else
  if [[ -z "${GH_PAT}" ]]; then
    if [[ -t 0 ]]; then
      echo ""
      warn "Images are private. You need a GitHub Personal Access Token (PAT)"
      warn "with the  read:packages  scope to pull them."
      echo ""
      echo -e "  Create a PAT at: ${BOLD}https://github.com/settings/tokens${NC}"
      echo -e "  Then enter it below (input is hidden):"
      echo ""
      read -r -s -p "  GitHub PAT: " GH_PAT
      echo ""
    else
      error "Images are private but no PAT was provided.\n\n  Re-run with your token:\n  curl -fsSL ...install.sh | bash -s -- \"ghp_YOUR_TOKEN\""
    fi
  else
    info "Using provided PAT for GHCR login."
  fi
  echo "${GH_PAT}" | docker login ghcr.io -u "${GITHUB_OWNER}" --password-stdin \
    || error "GHCR login failed. Check your PAT has 'read:packages' scope."
  success "Logged in to ghcr.io."
fi

# ── 6. Pull latest images ─────────────────────────────────────────────────────
step "Pulling latest Docker images"

docker compose pull
success "All images up to date."

# ── 7. Start / restart services ───────────────────────────────────────────────
if $IS_UPDATE; then
  step "Restarting Exchange Manager with latest images"
  docker compose up -d --remove-orphans
else
  step "Starting Exchange Manager"
  docker compose up -d
fi

# ── 8. Wait for API health ────────────────────────────────────────────────────
step "Waiting for services to become healthy"

ATTEMPTS=0; MAX=36   # up to 3 minutes
echo -n "  "
until docker compose ps --format '{{.Service}} {{.Health}}' 2>/dev/null \
      | grep -q "^api healthy" || [[ $ATTEMPTS -ge $MAX ]]; do
  sleep 5
  ATTEMPTS=$((ATTEMPTS + 1))
  echo -n "."
done
echo ""

if [[ $ATTEMPTS -ge $MAX ]]; then
  warn "API is still starting up. Check logs with:"
  warn "  docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f api"
else
  success "All services are up and healthy!"
fi

# ── 9. Done ───────────────────────────────────────────────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")
PUBLIC_URL_VAL=$(grep -E '^CORS_ORIGIN=' .env 2>/dev/null | cut -d= -f2 || echo "http://${SERVER_IP}")

echo ""
echo -e "${GREEN}${BOLD}"
echo "  ╔════════════════════════════════════════════════════╗"
if $IS_UPDATE; then
echo "  ║   Exchange Manager updated successfully!           ║"
else
echo "  ║   Exchange Manager is running!                     ║"
fi
echo "  ╠════════════════════════════════════════════════════╣"
printf  "  ║   Web UI:  %-40s║\n" "${PUBLIC_URL_VAL}  "
echo "  ║                                                    ║"
if ! $IS_UPDATE; then
echo "  ║   Default login:  admin  /  admin1234              ║"
echo "  ║   ⚠  You will be forced to change the password     ║"
echo "  ║      on first login.                               ║"
fi
echo "  ╚════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo "  Useful commands (run from ${BOLD}${INSTALL_DIR}${NC}):"
echo ""
echo "    View live logs:   docker compose logs -f"
echo "    Stop:             docker compose down"
echo "    Update to latest: bash <(curl -fsSL ${REPO_RAW}/exchange-system/deploy/install.sh) \"${GH_PAT:+<YOUR_PAT>}\""
echo ""
